project:
  type: website
  output-dir: docs/
website:
  google-analytics: 
    tracking-id: "asdas"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Please see left-sidebar for definitions"
    type: info
    position: below-navbar  
  title: "FHCC Flow Core"
  site-path: "/InstrumentQC/"
  navbar:
    logo: images/hex.png
    left:
    - text: "Home"
      href: index.qmd
    - text: "Levey-Jennings Plots"
      menu:
      - text: "Cytek Aurora 1"
        href: Aurora-1.html
      - text: "BD Symphony 2"
        href: Symphony-2.html
      - text: "Fortessa"
        href: Fortessa.html  
    - text: "Historical"
      menu:
      - text: "Cytek Aurora 1"
        href: https://umgccfcss.github.io/Aurora5L/
    right:
    - text: "Help"
      href: help.qmd
    - text: "Download Data"
      href: Data.qmd
    - text: "Other"
      menu:
      - text: "Miscellaneous"
        href: Miscellaneous.qmd 
      - text: "QC Bead Lots"
        href: CytekQCBead.qmd
      - text: "Bleach Vs. QC Bead Lot 2006"
        href: BleachVsLot2006Beads.qmd
    - icon: github
      href: https://github.com/ncolven/InstrumentQC
      aria-label: GitHub
  page-footer:
    background: light
    left: Fred Hutch Cancer Center, Seattle
    right: Built with [Quarto](https://quarto.org/). How? [Find Out](https://davidrach.github.io/InstrumentQC_Install/){target=_blank}

format:
  html:
    theme: styles.scss